version: '3.8'

networks:
  shared-network:
    name: shared-network
    driver: bridge

services:
  gateway-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-api
    ports:
      - "8180:8180"
    networks:
      - shared-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared-network
