version: '3.8'

networks:
  shared-network:
    name: shared-network
    external: true
    driver: bridge

services:
  gateway-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-api
    expose:
      - "8180"
    ports:
      - "8180:8180"
    networks:
      - shared-network