spring:
  security:
    enabled: false
  cloud:
    gateway:
      routes:
        - id: Authentication
          uri: http://auth-api:8005
          predicates:
            - Path=/auth/**
        - id: Books
          uri: http://book-api:8006
          predicates:
            - Path=/book-api/**
        - id: Loans
          uri: http://book-rent-api:8080
          predicates:
            - Path=/loans**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

# Enable the JwtAuthenticationFilter in Gateway
server:
  port: 8180


