spring:
  cloud:
    gateway:
      routes:
        - id: Authentication
          uri: http://auth-api:8005
          predicates:
            - Path=/auth/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allowedMethods: "*"
            allowedHeaders: "*"

# Enable the JwtAuthenticationFilter in Gateway
server:
  port: 8180
